'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.18444
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MyGSM.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 CREATE TABLE IF NOT EXISTS [Contacts] (
        '''  [ID] INTEGER NOT NULL ON CONFLICT FAIL PRIMARY KEY AUTOINCREMENT, 
        '''  [Name] TEXT, 
        '''  [Number] TEXT, 
        '''  [Remark] TEXT);
        '''
        '''
        '''CREATE TABLE IF NOT EXISTS [ReadySend] (
        '''  [ID] INTEGER NOT NULL ON CONFLICT FAIL PRIMARY KEY AUTOINCREMENT, 
        '''  [Time] DATETIME, 
        '''  [RemoteAddress] TEXT, 
        '''  [RemoteAddressType] CHAR, 
        '''  [Message] TEXT);
        '''
        '''
        '''CREATE TABLE IF NOT EXISTS [Received] (
        '''  [ID] INTEGER NOT NULL ON CONFLICT FAIL PRIMARY KEY AUTOINCREMENT, 
        '''  [Time] DATETIME, [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ddl() As String
            Get
                Return ResourceManager.GetString("ddl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 0000 操作已成功完成。
        '''0001 错误的函数。
        '''0002 系统找不到指定的文件。
        '''0003 系统找不到指定的路径。
        '''0004 系统无法打开文件。
        '''0005 拒绝访问。
        '''0006 句柄无效。
        '''0007 存储区控制块已损坏。
        '''0008 可用的存储区不足，无法执行该命令。
        '''0009 存储区控制块地址无效。
        '''0010 环境错误。
        '''0011 试图使用不正确的格式加载程序。
        '''0012 访问代码无效。
        '''0013 数据无效。
        '''0014 可用的存储区不足，无法完成该操作。
        '''0015 系统找不到指定的驱动器。
        '''0016 无法删除该目录。
        '''0017 系统无法将文件移到其他磁盘驱动器上。
        '''0018 没有其他文件。
        '''0019 媒体写保护。
        '''0020 系统找不到指定的设备。
        '''0021 设备尚未准备好。
        '''0022 设备无法识别该命令。
        '''0023 数据错误（循环冗余检查）。
        '''0024 程序发出命令，但是该命令的长度错误。
        '''0025 驱动器在磁盘上无法定位指定的区域或磁道。
        '''0026 无法访问指定的磁盘或软盘。
        '''0027 驱动器找不到所请求的扇区。
        '''0028 打印机缺纸。
        '''0029 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Win32Errors() As String
            Get
                Return ResourceManager.GetString("Win32Errors", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
